In [1]:
import pandas as pd

In [2]:
with open("a.txt", "wb") as file:
    content = file.read(10)
    file.tell()
    file.seek(10)
    print(content)
#can't read when mode is wb, and wb is anyways for binary files

UnsupportedOperation: read

In [3]:
pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [4]:
data_frame = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
data_frame

   A  B
0  1  4
1  2  5
2  3  6

In [5]:
data_frame.loc[1:2, 'A']

1    2
2    3
Name: A, dtype: int64

In [6]:
data_frame.iloc[1, 0]

np.int64(2)

In [7]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 
                   'Age': [4, 5, 6],
                    'Salary': [50000, 60000, None],
  'Department': [1, 2, 3],
  'Manager':[None, 'John', None],
   'skills': [['Python', 'SQL'], ['Java', 'C++'], None]})

df_new = df[(df['Age'] > 4) & (df['Salary'] < 60000)]
df_new

Empty DataFrame
Columns: [Name, Age, Salary, Department, Manager, skills]
Index: []

In [8]:
df.isna()

    Name    Age  Salary  Department  Manager  skills
0  False  False   False       False     True   False
1  False  False   False       False    False   False
2  False  False    True       False     True    True

In [9]:
df.fillna({'Manager': 'Unknown'}, inplace=True)

In [10]:
df.fillna({'Salary': df['Salary'].mean()}, inplace=True)

In [11]:
df.dropna(subset=['Salary'], inplace=True)
df

      Name  Age   Salary  Department  Manager         skills
0    Alice    4  50000.0           1  Unknown  [Python, SQL]
1      Bob    5  60000.0           2     John    [Java, C++]
2  Charlie    6  55000.0           3  Unknown           None

In [12]:
df.dropna()

    Name  Age   Salary  Department  Manager         skills
0  Alice    4  50000.0           1  Unknown  [Python, SQL]
1    Bob    5  60000.0           2     John    [Java, C++]

In [13]:
department_df = pd.DataFrame({"id": [1, 2, 3, 4],
                              "department_name": ["HR", "IT", "Finance", "Technical"]})

In [14]:
df_merged = pd.merge(df, department_df, 
                     left_on='Department', 
                     right_on='id', how='outer')
df_merged

,Name,Age,Salary,Department,Manager,skills,id,department_name
0,Alice,4.0,50000.0,1.0,Unknown,"[Python, SQL]",1,HR
1,Bob,5.0,60000.0,2.0,John,"[Java, C++]",2,IT
2,Charlie,6.0,55000.0,3.0,Unknown,None,3,Finance
3,NaN,NaN,NaN,NaN,NaN,NaN,4,Technical

In [15]:
df_additional = pd.DataFrame({'Name': ['ABC', 'PQR', 'XYZ'], 
                   'Age': [14, 15, 16],
                    'Salary': [None, 60000, 40000],
  'Department': [4, 2, 1],
  'Manager':['Alice', 'Bob', 'Charlie'],
   'skills': [['Python', 'SQL'], ['Java', 'C++'], None]})

In [16]:
df_new = pd.concat([df, df_additional], ignore_index=True)
df_new

      Name  Age   Salary  Department  Manager         skills
0    Alice    4  50000.0           1  Unknown  [Python, SQL]
1      Bob    5  60000.0           2     John    [Java, C++]
2  Charlie    6  55000.0           3  Unknown           None
3      ABC   14      NaN           4    Alice  [Python, SQL]
4      PQR   15  60000.0           2      Bob    [Java, C++]
5      XYZ   16  40000.0           1  Charlie           None

In [17]:
df_weather = pd.DataFrame({'City': ['New York', 'Los Angeles', 'Chicago'],
                           'Temperature': [30, 25, 20],
                           'Humidity': [70, 60, 80], 'Date': ['2023-01-01', '2023-01-02', '2023-01-03']})
df_weather

          City  Temperature  Humidity        Date
0     New York           30        70  2023-01-01
1  Los Angeles           25        60  2023-01-02
2      Chicago           20        80  2023-01-03

In [18]:
df_weather.transpose()

                      0            1           2
City           New York  Los Angeles     Chicago
Temperature          30           25          20
Humidity             70           60          80
Date         2023-01-01   2023-01-02  2023-01-03

In [19]:
new_row = {"City": "New York", "Temperature": 40, "Humidity": 60, "Date": "2024-01-01"}

new_row = {"City": "New York", "Temperature": 32, "Humidity": 60, "Date": "2024-01-02"}
df_weather.loc[len(df_weather)] = new_row
df_weather['year'] = pd.to_datetime(df_weather['Date']).dt.year
df_weather

          City  Temperature  Humidity        Date  year
0     New York           30        70  2023-01-01  2023
1  Los Angeles           25        60  2023-01-02  2023
2      Chicago           20        80  2023-01-03  2023
3     New York           32        60  2024-01-02  2024

In [20]:

df_weather.pivot_table(index='City', columns='year', values='Temperature', aggfunc='mean')

year         2023  2024
City
Chicago      20.0   NaN
Los Angeles  25.0   NaN
New York     30.0  32.0